### ISSUE TITLE
Apply for UKRI grant

### ISSUE THREAD

**Issue by ChristinaLast** [AQ-AI/open-geo-engine#18]
- [ ]  Apply to this [UKRI Grant](https://www.ukri.org/opportunity/reducing-global-health-non-communicable-disease-risk-for-young-people/)
- [ ] Attend webinar on 7th Feb

**Comment by ChristinaLast** [comment]
Notes on the GADC call:
# GADC Intro to funding application
### Key stats:
- Link to funding page: https://www.ukri.org/opportunity/reducing-global-health-non-communicable-disease-risk-for-young-people/
- Size of fund: £5,000,000
- Pre-app deadline: 19 April 2022 23:59 
- Full Application: 31st May 11:59 UTC


### Keywords
- NCDs: Noncommunicable diseases


#### Target illnesses:
- "implementation research"
    - "Know-Do" gap for NCDs
- Free access to "e-hub" to apply successfully
    - You can access the GACD Implementation Science e-Hub here: https://implementationscience-gacd.org/
- Collaborative research network:
    - You can explore the activities of GACD working groups here: https://gacd.org/community/research-network/working-groups
- Previous funds
    - ![](https://i.imgur.com/twqXZwQ.png)
    - Moving away from disease-specific grants to communities and multiple morbidity
    - Take a look at GACD projects funded through previous grant calls: https://gacd.org/community/research-network/projects

### Current funding call
- The home webpage for GACD’s seventh funding call: https://gacd.org/funding/current-call-for-applications/common-risk-factors
    - LMICs ot disadvantaged populations in HICs
- Achieve: impactful sustainable research to address health inequity
    - provide recommendations to international orgs on regional/national/international  health inequity
- Members funding the call
![](https://i.imgur.com/a1EDMwQ.png)
- Qualified research teams
![](https://i.imgur.com/YnB2YB1.png)
- Access a specially curated set of stakeholder engagement resources here: https://gacd.org/resources/researchers-and-students/stakeholder-engagement
- Find a collaborator tool
- The full text for the seventh GACD funding call can be accessed here: https://gacd.org/perch/resources/full-call-text.pdf (please note this is a link directly to a pdf)

### Call: A life course approach to common NCD risk factor prevention and reduction: Implementation research to reduce the NCD burden by targeting critical life stages and key transitions between life stages

#### Implementation research
- "Which evidenced-based policy is the best for a new context or taget-based group"
    - A collection of case studies relevant to different stages of implementation research of NCD prevention and control policies, programs, and strategies can be found on our e-Hub: https://implementationscience-gacd.org/case-studies/
    - You can read our impact case studies here: https://gacd.org/our-impact/case-studies

#### common NCD risk factors
- Controllable risk factors linked to the onset and progression of Multiple NCDs 
- multiple (one or more) to delay onset or delay progression
    - patients with and without NCDs

##### evidenced based intervention
- intervention can be single or package
    - clean air mentioned
- behavioural change
- health-potential of environments
    - e.g. app as behavioural
    - e.g. policy as environmental
        - e.g. WHO best buys
- encouraging digital health interventions
- encouraging multi-sectoral interventions

##### life-course approach
- target a specific critical period which can impact health into lifespan
    - e.g. first thousand days of life
        - improve the acceptability of intervention in this life stages
- most only focus on young people
    - e.g. 10-24 yrs
- **NOT** longitudinal studies

### Expected project outcomes
- 3-5 years
- measure implementation research outcomes
- health proxy outcomes
    - e.g. QUALYs and DALYs
- Health system
    - sex, gender and intersectional differences

### in other words...
![](https://i.imgur.com/5rcHdvB.png)

#### Scoring criteria
- relevance and quality of the project
- quality of the team
- feasibility of the project
- expected impact of the team
- policy influencer on project team can be helpful
- 

### How to submit
##### Co-funding
- PIs can only submit one app across all participating GACD funding agencies
    - @prithvi to apply to India?
    - Co-funding?
        - two PIs meets the eligibilty for separate agencies
        - priority can be for co-funding
![](https://i.imgur.com/rO7JuQk.png)
- must score amoung the top for **both**
- ICMR (india requires co-funding)
##### Pre-application
- [ ] Is this required for ICMR?
- Be aware if both require this (I know UKRI does)
##### Full-application
- Apply through GACD platform
- 15-page research plan (proposal)
    - GACD guidance for writing your research proposal: https://www.gacd.org/perch/resources/gacd-research-proposal-guidance.pdf
1. `Additonal Informtion -> Apply here`
2. `Sign up`
3. `Complete and Submit`

### Upcoming calls
###### Nov 2022
![](https://i.imgur.com/MxbnpAI.png)

#### Tasks
- [ ] check eligibility for NHIR/MCR and ICMR (India) in terms of:
    - [ ] our eligibility as researchers
    - [ ] the research remit of both local institutions
- [ ] Get at least one letter of support for project partners Institution
