### ISSUE TITLE
Milestone & Metrics

### ISSUE THREAD

**Issue by ChristinaLast** [AQ-AI/open-geo-engine#20]
#### Technical
- [x] get a working version of the PM2.5 prediction endpoint up and running locally)
- [x] decide on `mlflow` vs. `metaflow` for MLOps experiment-running tool
- [x] decided on cloud provider
  - @ChristinaLast already has £10,000 azure VM credits available from Turing
  - depends on, if UNICEF provide funding and *additional* access to cloud resources

#### Financial
- [x] drafted first iteration of application to #18 
- [x] shortlist funding sources to apply to at the 6 month horizon
